"""comments class

Revision ID: 00c3bfb58bda
Revises: 5b9e241f4333
Create Date: 2017-03-09 20:48:52.213390

"""

# revision identifiers, used by Alembic.
revision = '00c3bfb58bda'
down_revision = '5b9e241f4333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
