"""bug fix

Revision ID: 1dbc98833f5a
Revises: 3e09e0b9b235
Create Date: 2017-02-22 20:46:24.006587

"""

# revision identifiers, used by Alembic.
revision = '1dbc98833f5a'
down_revision = '3e09e0b9b235'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
