"""bug fix

Revision ID: 3e09e0b9b235
Revises: 501c1e831e96
Create Date: 2017-02-22 19:26:32.217238

"""

# revision identifiers, used by Alembic.
revision = '3e09e0b9b235'
down_revision = '501c1e831e96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
