"""personal information

Revision ID: 470d06c44aa2
Revises: d78891cca64a
Create Date: 2017-02-28 20:45:16.946338

"""

# revision identifiers, used by Alembic.
revision = '470d06c44aa2'
down_revision = 'd78891cca64a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
