"""confirmation function

Revision ID: 501c1e831e96
Revises: a174601d40ef
Create Date: 2017-02-22 18:04:11.873648

"""

# revision identifiers, used by Alembic.
revision = '501c1e831e96'
down_revision = 'a174601d40ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
