"""comments class

Revision ID: 5b9e241f4333
Revises: 556314040741
Create Date: 2017-03-09 20:41:55.823402

"""

# revision identifiers, used by Alembic.
revision = '5b9e241f4333'
down_revision = '556314040741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
