"""add user loader

Revision ID: a174601d40ef
Revises: 281540465c33
Create Date: 2017-02-19 18:27:39.021556

"""

# revision identifiers, used by Alembic.
revision = 'a174601d40ef'
down_revision = '281540465c33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
