"""add gravatar

Revision ID: b5ec331eddb8
Revises: d9bdda15437f
Create Date: 2017-02-28 18:23:01.242463

"""

# revision identifiers, used by Alembic.
revision = 'b5ec331eddb8'
down_revision = 'd9bdda15437f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
