"""bug fix

Revision ID: b7fb0a191921
Revises: 470d06c44aa2
Create Date: 2017-02-28 20:55:47.056807

"""

# revision identifiers, used by Alembic.
revision = 'b7fb0a191921'
down_revision = '470d06c44aa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
