"""empty message

Revision ID: b8aea1dcea4c
Revises: c368343d0e36
Create Date: 2017-03-02 01:11:27.012486

"""

# revision identifiers, used by Alembic.
revision = 'b8aea1dcea4c'
down_revision = 'c368343d0e36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
