"""comments class

Revision ID: bf58d8a32449
Revises: 00c3bfb58bda
Create Date: 2017-03-09 20:50:16.601228

"""

# revision identifiers, used by Alembic.
revision = 'bf58d8a32449'
down_revision = '00c3bfb58bda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
