"""empty message

Revision ID: c368343d0e36
Revises: 3b878114b8c6
Create Date: 2017-03-02 01:00:54.265622

"""

# revision identifiers, used by Alembic.
revision = 'c368343d0e36'
down_revision = '3b878114b8c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
