"""bug fix

Revision ID: c5007e05db1e
Revises: b7fb0a191921
Create Date: 2017-02-28 23:55:31.028169

"""

# revision identifiers, used by Alembic.
revision = 'c5007e05db1e'
down_revision = 'b7fb0a191921'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
