"""add gravatar

Revision ID: d78891cca64a
Revises: b5ec331eddb8
Create Date: 2017-02-28 18:25:16.167827

"""

# revision identifiers, used by Alembic.
revision = 'd78891cca64a'
down_revision = 'b5ec331eddb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
