"""add ping function

Revision ID: d9bdda15437f
Revises: 1dbc98833f5a
Create Date: 2017-02-28 14:30:20.421017

"""

# revision identifiers, used by Alembic.
revision = 'd9bdda15437f'
down_revision = '1dbc98833f5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
